In [68]:
import cv2
import numpy as np

In [69]:
image=cv2.imread('images/input.jpg')

In [30]:
image=cv2.circle(image,(30,30),60,(10,10,100))

In [31]:
cv2.imshow('',image)
cv2.waitKey()
cv2.destroyAllWindows()

In [58]:
image=cv2.rectangle(image, (0,0), (3000,3000), (127,50,127), -1)

In [59]:
cv2.imshow('',image)
cv2.waitKey()
cv2.destroyAllWindows()

In [60]:
image

array([[[127,  50, 127],
        [127,  50, 127],
        [127,  50, 127],
        ...,
        [127,  50, 127],
        [127,  50, 127],
        [127,  50, 127]],

       [[127,  50, 127],
        [127,  50, 127],
        [127,  50, 127],
        ...,
        [127,  50, 127],
        [127,  50, 127],
        [127,  50, 127]],

       [[127,  50, 127],
        [127,  50, 127],
        [127,  50, 127],
        ...,
        [127,  50, 127],
        [127,  50, 127],
        [127,  50, 127]],

       ...,

       [[127,  50, 127],
        [127,  50, 127],
        [127,  50, 127],
        ...,
        [127,  50, 127],
        [127,  50, 127],
        [127,  50, 127]],

       [[127,  50, 127],
        [127,  50, 127],
        [127,  50, 127],
        ...,
        [127,  50, 127],
        [127,  50, 127],
        [127,  50, 127]],

       [[127,  50, 127],
        [127,  50, 127],
        [127,  50, 127],
        ...,
        [127,  50, 127],
        [127,  50, 127],
        [127,  50, 127]]

In [75]:


image=cv2.putText(image, 'La Louvre', (1245,0), cv2.FONT_HERSHEY_COMPLEX, 2, (100,170,0), 3)
cv2.imshow("Hello World!", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
image.shape

(830, 1245, 3)

In [66]:
0,1245

(0, 1245)

In [88]:
arr1=np.array([[1,2]])

In [89]:
arr1

array([[1, 2]])

In [90]:
translation=np.array([[1,0,2],[0,1,3]])

In [91]:
np.dot(arr1,translation)

array([[1, 2, 8]])